name: test-workflow-main

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    name: "my first job"
    steps:
      - name: Print Start Message
        run: echo "Workflow started..."

      - name: Sleep for 30 seconds
        run: sleep 30

      - name: Print End Message
        run: echo "Workflow completed..."






