name: test-workflow-main

on:
  push:
    branches:
      - "main"

jobs:
  job1:
    name: Job1 - Log and Sleep Job
    runs-on: ubuntu-latest

    steps:
      - name: Print Start Message
        run: echo "Workflow started..."

      - name: Sleep for 50 seconds - 1
        run: sleep 50

      - name: Sleep for 50 seconds - 2
        run: sleep 50

      - name: Print End Message
        run: echo "Workflow started..."

  job2:
    name: Job2 - Log and Sleep Job
    runs-on: ubuntu-latest

    steps:
      - name: Print Start Message
        run: echo "Workflow started..."

      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Print End Message
        run: echo "Workflow completed!"


