name: test-workflow-main

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: first job
    runs-on: ubuntu-latest

    steps:
      - name: Print Start Message
        run: echo "Workflow started..."

      - name: Sleep for 50 seconds
        run: sleep 50

      - name: Print End Message
        run: echo "Workflow completed..."


